### ISSUE TITLE
pinned upgrade fails

### ISSUE THREAD

**Issue by rgl** [chocolatey/chocolatey-ansible#117] opened 2023-05-23 17:41 UTC
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

I've `rpi-imager` `1.7.4.1` installed, but when I try to upgrade it to `1.7.5`, the ansible module fails as:

```
TASK [rpi_imager : Install Raspberry Pi Imaging Utility] ***********************
fatal: [op2]: FAILED! => changed=false 
  command: C:\ProgramData\chocolatey\bin\choco.exe pin add --name rpi-imager --version 1.7.5 --yes --no-progress --limit-output
  msg: Error pinning package 'rpi-imager' at '1.7.5'
  rc: 1
  stderr: ''
  stderr_lines: <omitted>
  stdout: |-
    Trying to add a pin for rpi-imager
    Unable to find package named 'rpi-imager' (version '1.7.5') to pin. Please check to ensure it is installed.
  stdout_lines: <omitted>
```

### What is Expected?

Expected it to upgrade the package.

### How Did You Get This To Happen?

1. create a playbook with this task (full playbook task at https://github.com/rgl/my-windows-ansible-playbooks/blob/main/roles/rpi_imager/tasks/main.yml):
    ```yaml
    - name: Install Raspberry Pi Imaging Utility
      chocolatey.chocolatey.win_chocolatey:
        name: rpi-imager
        version: '{{ rpi_imager_version }}'
        pinned: true
        state: upgrade
    ```
1. executed ansible.

### System Details

* Operating System: Windows Server 2022 and Windows 11.
* Windows PowerShell version: 5.1
* Chocolatey CLI Version: 1.4.0
* Chocolatey Licensed Extension version:
* Chocolatey License type:
* Terminal/Emulator:

### Installed Packages

```bash
N/A
```

### Output Log

```bash
N/A
```

**Comment by rgl** [comment] 2023-06-20 20:27
I've tried again with chocolatey 2.0.0 (before it was using chocolatey 1.4.0) and it still errors out.

Before:

```console
# choco list | grep hwmonitor
hwmonitor 1.50.0.20230303

# choco pin | grep hwmonitor
hwmonitor|1.50.0.20230303
```

Error, after executing ansible:

```
TASK [base : Install HWMonitor] ************************************************
fatal: [op2]: FAILED! => changed=false 
  command: C:\ProgramData\chocolatey\bin\choco.exe pin add --name hwmonitor --version 1.51.0.20230619 --yes --no-progress --limit-output
  msg: Error pinning package 'hwmonitor' at '1.51.0.20230619'
  rc: 1
  stderr: ''
  stderr_lines: <omitted>
  stdout: |-
    Trying to add a pin for hwmonitor
    Unable to find package named 'hwmonitor' (version '1.51.0.20230619') to pin. Please check to ensure it is installed.
  stdout_lines: <omitted>
```

**Comment by pauby** [comment] 2023-06-21 05:33
In that last one there are two different versions mentioned: '1.50.0.20230303' and '1.51.0.20230619'.

Version '1.51.0.20230619' isn't installed (as confirmed by the first command) so can't be pinned.

That is of course unless I'm misreading this?

**Comment by vexx32** [comment] 2023-06-21 13:07
Hmm... Oh, I wonder. If you have it pinned _already_ and then to upgrade it, I don't think choco would let you do that without first removing the pin. So that might explain what you're seeing. From memory, when you try to `upgrade` a pinned package, choco emits a warning about it and then does nothing. It isn't an _error_ state, though, so the ansible module won't notice it. If you run your playbook with at least `-vvv` you'll see the logs from choco.exe which contain that info.

I pinned the `git` package and then tried to upgrade it on my local machine, and the behaviour looks like this:
```
PS C:\Users\Rain> choco pin add -n git
Chocolatey v2.0.0 Business
Trying to add a pin for git
Successfully added a pin for git v2.39.2.
PS C:\Users\Rain> choco pin list
Chocolatey v2.0.0 Business
git|2.39.2|
test|0.1.0|
PS C:\Users\Rain> choco upgrade git -y -s chocolatey
Chocolatey v2.0.0 Business
Upgrading the following packages:
git
By upgrading, you accept licenses for the packages.

You have git v2.39.2 installed. Version 2.41.0 is available based on your source(s).
git is pinned. Skipping pinned package.

Chocolatey upgraded 0/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Warnings:
 - git - git is pinned. Skipping pinned package.
PS C:\Users\Rain> $lastexitcode
0
```

Note the absence of an abnormal exit code. This is not an error state, it's doing exactly what has been asked of it by respecting the pin and not upgrading the package, so to the Ansible module it will simply not see an issue. I don't think it would register as `changed` either in the result, if memory serves, so you could use that as a conditional to determine whether you need to run your `pin` action if you wanted

You'll need to _unpin_ the package before you can upgrade it, so your playbook probably needs to look something like this:

```yml
- name: Unpin Raspberry Pi Imaging Utility
    name: rpi-imager
    pinned: false

- name: Install Raspberry Pi Imaging Utility
  chocolatey.chocolatey.win_chocolatey:
    name: rpi-imager
    version: '{{ rpi_imager_version }}'
    pinned: true
    state: upgrade
```

**Comment by vexx32** [comment] 2023-06-22 13:30
Gotcha, appreciate the clarification! Currently 

After discussing with the team I think this is something we agree is useful, but is currently expected behaviour. We also think it's not something that this module should go out of the way to implement custom handling for at this point.

This has been raised previously as an issue for choco itself (see chocolatey/choco#2050) and we think it would be most suitable to wait until choco supports the functionality before implementing it in the collection here, so that we don't need to re-do the handling _again_ after choco adds support for it itself. There appears to be an open and recently-active PR for the linked issue, so it's likely that it will end up in choco in future.

For now, I'm going to close this issue, as it's not really a bug. When choco adds this functionality, we can revisit this and add proper handling for it at that point.

Thank you for filing the issue and being so responsive, it's genuinely very much appreciated! 💖

**Closed by vexx32** 2023-06-22 13:30 UTC
Labels: 0 - Waiting on User
