### ISSUE TITLE
Test Ansible collection to remain certified

### ISSUE THREAD

**Issue by adilio** [chocolatey/chocolatey-ansible#61] opened 2021-12-16 18:29 UTC
Ansible Partner Engineering has informed us that, in order to remain certified, this collection must support at least 2 versions of Ansible Core, and because 2.9 will be going end of life in December 2022, it will need to test for an additional version.

We are required to test the above collections for 2.11 . There is a guide for how to do this here:
https://connect.redhat.com/blog/testing-content-collections-ansible-automation-platform-20

We can reach out to ansiblepartners@redhat.com (Ansible Partner Engineering) if we require any further information.

**Comment by vexx32** [comment] 2022-01-13 16:07
Marking this as a duplicate of #57 and tracking the work there. Thanks for the additional info! 💖

**Closed** 2022-01-13 16:07 UTC
Labels: Duplicate Issue, Build Automation
